import { Transaction, RecurrenceRule } from '../types';
import { getStoredTransactions, saveStoredTransactions } from './storage';
import { fetchTransactions, upsertTransactions } from './database';
import { parseISO, addWeeks, addMonths, addYears, isBefore, isAfter, isEqual, startOfDay, addDays } from 'date-fns';

export function getNextOccurrenceDate(date: Date, frequency: string): Date {
  switch (frequency) {
    case 'semanal':
      return addWeeks(date, 1);
    case 'quinzenal':
      return addWeeks(date, 2);
    case 'mensal':
      return addMonths(date, 1);
    case 'bimestral':
      return addMonths(date, 2);
    case 'anual':
      return addYears(date, 1);
    default:
      return addMonths(date, 1);
  }
}

export function generateOccurrencesForRule(rule: RecurrenceRule, existingTransactions: Transaction[], windowDays = 90): Transaction[] {
  if (rule.isPaused) return [];
  
  const ruleStartDate = startOfDay(parseISO(rule.startDate));
  const windowEndDate = addDays(startOfDay(new Date()), windowDays);
  const ruleEndDate = rule.endDate ? startOfDay(parseISO(rule.endDate)) : null;
  
  const endLimit = ruleEndDate && isBefore(ruleEndDate, windowEndDate) ? ruleEndDate : windowEndDate;
  
  // Find the latest occurrence generated by this rule to know where to continue
  const generatedForRule = existingTransactions.filter(t => t.recurrenceRuleId === rule.id);
  
  let currentDate = ruleStartDate;
  
  if (generatedForRule.length > 0) {
    // Sort to find the latest
    generatedForRule.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const latestDate = startOfDay(parseISO(generatedForRule[0].date));
    currentDate = getNextOccurrenceDate(latestDate, rule.frequency);
  }
  
  const newOccurrences: Transaction[] = [];

  while (isBefore(currentDate, endLimit) || isEqual(currentDate, endLimit)) {
    // Generate transaction
    const dateStr = currentDate.toISOString().split('T')[0];
    
    // Check if it already exists (just to be safe against duplicates on same day)
    const exists = generatedForRule.some(t => t.date === dateStr);
    
    if (!exists) {
      newOccurrences.push({
        id: `rec_${rule.id}_${dateStr}`,
        date: dateStr,
        title: rule.title,
        amount: rule.amount,
        type: rule.type,
        category: rule.category,
        tagCode: rule.tagCode,
        paymentMethod: rule.paymentMethod,
        createdAt: new Date().toISOString(),
        recurrenceRuleId: rule.id,
        recurrenceModified: false,
      });
    }

    currentDate = getNextOccurrenceDate(currentDate, rule.frequency);
  }

  return newOccurrences;
}

export function syncRecurrences(rules: RecurrenceRule[]) {
  const existingTransactions = getStoredTransactions();
  let modified = false;
  let allNewOccurrences: Transaction[] = [];

  rules.forEach(rule => {
    const newOccurrences = generateOccurrencesForRule(rule, existingTransactions);
    if (newOccurrences.length > 0) {
      allNewOccurrences = [...allNewOccurrences, ...newOccurrences];
      modified = true;
    }
  });

  if (modified) {
    saveStoredTransactions([...existingTransactions, ...allNewOccurrences]);
  }
}

export async function syncRecurrencesSupabase(rules: RecurrenceRule[]): Promise<Transaction[]> {
  const existingTransactions = await fetchTransactions();
  let allNewOccurrences: Transaction[] = [];

  rules.forEach(rule => {
    const newOccurrences = generateOccurrencesForRule(rule, existingTransactions);
    if (newOccurrences.length > 0) {
      allNewOccurrences = [...allNewOccurrences, ...newOccurrences];
    }
  });

  if (allNewOccurrences.length > 0) {
    await upsertTransactions(allNewOccurrences);
  }

  return allNewOccurrences;
}

